[book]
title = "Nautilus: numerical computing for Chelis"
authors = ["Chelis contributors"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Chelis-Lang/nautilus"
